#!/usr/bin/perl -w
#
# Make alpha-g geometry files for display
#

my $r0 = 109.25;
my $r1 = 22.2275;
my $len = 144 / $r0;
my $numFaces = 24;
my $pi = 3.14159265358979;

printf "RN= %.1f\n", $r0;
printf "N= %d\n", 4 * $numFaces;
printf "F= %d\n", 2 * $numFaces;
printf "E= %d\n", 6 * $numFaces;

my $i;
for ($i=0; $i<$numFaces; ++$i) {
    my $a = $i * $pi * 2 / $numFaces;
    my $cos = cos($a);
    my $sin = sin($a);
    printf "N, %.6f, %.6f, %.6f,  * %d\n", $cos, $sin, -$len, $i*2+1;
    printf "N, %.6f, %.6f, %.6f,  * %d\n", $cos, $sin, $len, $i*2+2;
}
for ($i=0; $i<$numFaces; ++$i) {
    my $a = $i * $pi * 2 / $numFaces;
    my $cos = cos($a) * $r1/$r0;
    my $sin = sin($a) * $r1/$r0;
    printf "N, %.6f, %.6f, %.6f,  * %d\n", $cos, $sin, -$len, ($i+$numFaces)*2+1;
    printf "N, %.6f, %.6f, %.6f,  * %d\n", $cos, $sin, $len, ($i+$numFaces)*2+2;
}
for ($i=0; $i<$numFaces; ++$i) {
    my $n0 = $i * 2 + 1;
    my $n1 = (($i*2 + 2) % ($numFaces * 2)) + 1;
    printf "F, 4, %d, %d, %d, %d,  * %d\n", $n0, $n0+1, $n1+1, $n1, $i + 1;
}
for ($i=0; $i<$numFaces; ++$i) {
    my $o = $numFaces * 2;
    my $n0 = $i * 2 + $o + 1;
    my $n1 = (($i*2 + 2) % ($numFaces * 2)) + $o + 1;
    printf "F, 4, %d, %d, %d, %d,  * %d\n", $n0, $n0+1, $n1+1, $n1, $i + $numFaces+1;
}
for ($i=0; $i<$numFaces; ++$i) {
    my $n0 = $i * 2 + 1;
    my $n1 = (($i*2 + 2) % ($numFaces * 2)) + 1;
    printf "E, %d, %d,  * %d\n", $n1, $n0, $i*3+1;
    printf "E, %d, %d,  * %d\n", $n0, $n0+1, $i*3+2;
    printf "E, %d, %d,  * %d\n", $n0+1, $n1+1, $i*3+3;
}
for ($i=0; $i<$numFaces; ++$i) {
    my $o = $numFaces * 2;
    my $n0 = $i * 2 + $o + 1;
    my $n1 = (($i*2 + 2) % ($numFaces * 2)) + $o + 1;
    printf "E, %d, %d,  * %d\n", $n1, $n0, $i*3+1 + 3 * $numFaces;
    printf "E, %d, %d,  * %d\n", $n0, $n0+1, $i*3+2 + 3 * $numFaces;
    printf "E, %d, %d,  * %d\n", $n0+1, $n1+1, $i*3+3 + 3 * $numFaces;
}
